remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"

title: "基憶"
subtitle: "기억 속에서 사라져가는 국가유산을 간직하는 장소"
name: "30419 김하연 | 30518 김서연"
description: "사라져가는 국가유산을 기록합니다."
copyright: "30419 김하연 | 30518 김서연"

# 사이드바/댓글/공유 비활성화
author:
  name: "기억 프로젝트"
  links: 

footer:
  links:
  since: "2026"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      comments: false
      share: false
      related: false
